title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     tyler-bowers-test
  repo:     tylerbowers

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond
  with: 01_first-response.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title: create route
  description: create route
  event: push
  actions: 
  - type: Merge_PR

# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
 - title: create pr
  description: create pr
  event: pull_request
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: Merge_PR

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
 - title: comment1
  description: comment
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: Merge_PR

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
 - title: push more
  description: push more
  event: push
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: Merge_PR

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
 - title: comment2
  description: comment
  event: commit_comment
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: Merge_PR
