title: Node student lab
tagline: Node learning lab for students
description: A github learning lab for students to learn Node and how it works and what not.

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     tyler-bowers-test
  repo:     tylerbowers

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond
  with: 01_first-response.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title: create route
  description: create route
  event: push
  actions: 
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: "Creating the config file"
    else:
    - type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md
